#!/usr/bin/env bash

[[ ! -d ./torch-server ]] && \
  wget https://build.torchapi.com/job/Torch/job/master/lastSuccessfulBuild/artifact/bin/torch-server.zip \
  && unzip -d torch-server torch-server.zip


[[ "$(stat -c '%u' torch-server)" != "1000" ]] && (
  echo "Setting owner of torch-server to UID 1000"
  chown -R 1000:1000 torch-server
)

docker-compose up -d && docker-compose logs -f
